version: '3.4'

services:
  swimpool:
    container_name: swimpool
    image: handsome16/swim-pool-spring:latest
    build:
      context: .
      dockerfile: ./swimpool/Dockerfile
    ports:
      - "8080:8080"

  pdf-consumer-resignation:
    image: handsome16/pdf-consumer-resignation:latest
    build:
      context: .
      dockerfile: ./PdfResignationConsumer/Dockerfile
    ports:
      - "8082:8080"
  pdf-consumer-promotion:
    image: handsome16/pdf-consumer-promotion:latest
    build:
      context: .
      dockerfile: ./PdfPromotionConsumer/Dockerfile
    ports:
      - "8081:8080"
  pdf-consumer-report:
    image: handsome16/pdf-consumer-report:latest
    build:
      context: .
      dockerfile: ./PdfReportConsumer/Dockerfile
    ports:
      - "8083:8080"
  redis-jwt:
    container_name: redis_jwt_cont
    image: "redis:alpine"
    ports:
      - "6379:6379"


  swimpool-data-db:
    container_name: swimpool_data_db
    image: postgres:12.7
    restart: always
    environment:
      - POSTGRES_USER=qwerty007
      - POSTGRES_PASSWORD=qwerty007
      - POSTGRES_DB=basin_db
    command: ["--autovacuum=off"]
    ports:
      - "127.0.0.1:5433:5432"

  rabbitmq-queue:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-queue'
    ports:
      - 5672:5672
      - 15672:15672